language: android
jdk: oraclejdk8
before_install:
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-28"

env:
  global:
    - ANDROID_API_LEVEL=28
    - ANDROID_BUILD_TOOLS_VERSION=28.0.3
    - TRAVIS_SECURE_ENV_VARS=true

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools

    # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION

    # The SDK version used to compile your project
    - android-$ANDROID_API_LEVEL

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-google-android-support
  licenses:
    - '.+'

script:
  - ./gradlew clean
  - ./gradlew assembleRelease